[project]
name = "3d-rendering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "imageio>=2.37.2",
    "pillow>=12.1.0",
    "pygltflib>=1.16.5",
    "ursina>=7.0.0",
]
