[project]
name = "3d-rendering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "panda3d>=1.10.16",
    "ursina>=7.0.0",
]
